name: ibdfw
version: '0.1.1'
summary: Iptables based firewall rules manager
description: |
  ibdfw is an iptables rules manager with advanced features

base: core18

grade: devel
confinement: classic

apps:
  ibdfw:
    command: ibdfw
  daemon:
    command: ibdfw auto
    daemon: oneshot

parts:
  ibdfw:
    source: src/
    plugin: dump
#  network-utils:
#    plugin: nil
#    override-pull: ""
#    stage-packages:
#    - iptables
#    - gawk
#    - sed
#    - grep
