name: ibdfw
version: '0.3.4'
summary: Iptables based firewall rules manager
description: |
  ibdfw is an iptables rules manager with advanced features

base: core20

grade: stable
confinement: strict

apps:
  ibdfw:
    command: ibdfw
    plugs: [ firewall-control ]

  daemon:
    command: ibdfw auto
    plugs: [ firewall-control ]
    daemon: oneshot

parts:
  ibdfw:
    source: src/
    plugin: dump
    stage-packages:
    - conntrack
    - ipset
    - iptables
    - nano
