name: ibdfw
version: '0.0.89'
summary: Iptables based firewall rules manager
description: |
  ibdfw is an iptables rules manager with advanced features

base: core18

grade: devel
confinement: strict

passthrough:
  layout:
    /etc/ibdfw/conf.d:
      bind: $SNAP/etc/ibdfw/conf.d

apps:
  ibdfw:
    command: ibdfw
  daemon:
    command: ibdfw auto
    daemon: oneshot

parts:
  ibdfw:
    source: src/
    plugin: dump
#  network-utils:
#    plugin: nil
#    override-pull: ""
#    stage-packages:
#    - iptables
#    - gawk
#    - coreutils
#    - sed
#    - grep
