#!/bin/bash
#--------------------------------------------------------------------------
# Default : Defines default action for input/output
#
# patterns :
# 	Default <input|output> <accept/drop/reject>
#
# examples :
# 	Default input drop
# 	Default forward drop
# 	Default output accept
#--------------------------------------------------------------------------
function Default {
	case $1 in
		input) chain=INPUT ;;
		output) chain=OUTPUT ;;
		forward) chain=FORWARD ;;
		*) die "Chain $1 is not a valid chain ($@)" ;;
	esac

	case $2 in
		accept) action=ACCEPT ;;
		reject) action=REJECT ;;
		drop) action=DROP ;;
		*) die "Action $1 is not a valid action ($@)" ;;
	esac

	fw-addDescription $PRIO_STD [$1][default]=$action
	fw-addRule $PRIO_STD -P $chain $action
}
