#!/bin/bash
#--------------------------------------------------------------------------
# Nat : provide internet access to private network
#
# patterns :
#       Nat unidirectionnal <ip/network> via <ip>
#		Nat forward <outside-ip>:<port> to <inside-ip>:<port>
#
# examples :
#       Nat unidirectionnal 10.0.0.0/8 via 5.6.7.8
# 		Nat bidirectionnal 10.0.0.1 via 4.4.4.4
#		Nat port-forward 5.6.7.8:1022 to 10.0.0.1:22
#--------------------------------------------------------------------------

function Nat {
	fw-addDescription $PRIO_NAT Nat $@

	case $1 in
       	unidirectionnal)
			inside="$2"
			outside="$4"
			fw-addRule $PRIO_NAT -t nat -A POSTROUTING -j SNAT -s "$inside" '!' -d "$inside"  --to "$outside"
			;;
		bidirectionnal)
			inside="$2"
			outside="$4"
			fw-addRule $PRIO_NAT -t nat -A POSTROUTING -j SNAT -s "$inside" --to "$outside"
			fw-addRule $PRIO_NAT -t nat -A PREROUTING -j DNAT -d "$outside" --to "$inside"
			;;
		port-forward)
			ip=$(echo $2 | sed 's/:.*//g')
			port=$(echo $2 | sed 's/.*://g')
			dest="$4"
			fw-addRule $PRIO_NAT -t nat -A PREROUTING -p tcp -d $ip --dport $port -j DNAT --to-destination $dest
			;;
		*)
			die "Unknown pattern Nat $*"
			;;
	esac
}

